server:
  port: 8080

spring:
  application:
    name: cyber-treatment

  datasource:
    url: jdbc:mysql://localhost:3308/cyber-treatment?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: medical-platform-secret-key-2026
  expire: 7776000000  # 90? = 90 × 24 × 60 × 60 × 1000